# Generated by Django 3.2.5 on 2022-12-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
