# Generated by Django 3.2.5 on 2022-12-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='carmodel',
            new_name='car',
        ),
    ]
